/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package registrasibpjs;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Kode
 */
public class DlgCekSEPKunjunganPertama extends javax.swing.JDialog {

    private final sekuel Sequel = new sekuel();
    private final DlgRegistrasiSEP form = new DlgRegistrasiSEP(null, false);

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param id
     */
    public DlgCekSEPKunjunganPertama(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new javax.swing.JPanel();
        labelKeterangan = new javax.swing.JLabel();
        textCekNoKartu = new javax.swing.JTextField();
        btnKonfirm = new widget.Button();
        btnTutup = new widget.Button();
        jPanel3 = new javax.swing.JPanel();
        btnAngka7 = new javax.swing.JButton();
        btnAngka8 = new javax.swing.JButton();
        btnAngka9 = new javax.swing.JButton();
        btnAngka4 = new javax.swing.JButton();
        btnAngka5 = new javax.swing.JButton();
        btnAngka6 = new javax.swing.JButton();
        btnAngka1 = new javax.swing.JButton();
        btnAngka2 = new javax.swing.JButton();
        btnAngka3 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAngka0 = new javax.swing.JButton();
        btnAngkaHps = new javax.swing.JButton();
        empty1 = new javax.swing.JLabel();
        empty2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/bpjs-amiz.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelKeterangan.setForeground(new java.awt.Color(0, 131, 62));
        labelKeterangan.setText("No. RM / KTP / Peserta BPJS : ");
        labelKeterangan.setFocusable(false);
        labelKeterangan.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 20;
        jPanel1.add(labelKeterangan, gridBagConstraints);

        textCekNoKartu.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        textCekNoKartu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCekNoKartu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        textCekNoKartu.setPreferredSize(new java.awt.Dimension(800, 75));
        textCekNoKartu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCekNoKartuKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(textCekNoKartu, gridBagConstraints);

        btnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        btnKonfirm.setMnemonic('U');
        btnKonfirm.setText("CEK");
        btnKonfirm.setToolTipText("Alt+U");
        btnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKonfirm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnKonfirm.setPreferredSize(new java.awt.Dimension(150, 75));
        btnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        jPanel1.add(btnKonfirm, gridBagConstraints);

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnTutup.setMnemonic('U');
        btnTutup.setText("BATAL");
        btnTutup.setToolTipText("Alt+U");
        btnTutup.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnTutup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTutup.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTutup.setPreferredSize(new java.awt.Dimension(150, 75));
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.5;
        jPanel1.add(btnTutup, gridBagConstraints);

        jPanel3.setPreferredSize(new java.awt.Dimension(294, 402));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnAngka7.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka7.setText("7");
        btnAngka7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka7, gridBagConstraints);

        btnAngka8.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka8.setText("8");
        btnAngka8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka8, gridBagConstraints);

        btnAngka9.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka9.setText("9");
        btnAngka9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka9, gridBagConstraints);

        btnAngka4.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka4.setText("4");
        btnAngka4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka4, gridBagConstraints);

        btnAngka5.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka5.setText("5");
        btnAngka5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka5, gridBagConstraints);

        btnAngka6.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka6.setText("6");
        btnAngka6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka6, gridBagConstraints);

        btnAngka1.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka1.setText("1");
        btnAngka1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka1, gridBagConstraints);

        btnAngka2.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka2.setText("2");
        btnAngka2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka2, gridBagConstraints);

        btnAngka3.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka3.setText("3");
        btnAngka3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka3, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnClear.setText("C");
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnClear, gridBagConstraints);

        btnAngka0.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngka0.setText("0");
        btnAngka0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngka0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngka0, gridBagConstraints);

        btnAngkaHps.setFont(new java.awt.Font("Inter Display Semibold", 0, 40)); // NOI18N
        btnAngkaHps.setText("←");
        btnAngkaHps.setToolTipText("");
        btnAngkaHps.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAngkaHps.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAngkaHps.setMaximumSize(new java.awt.Dimension(75, 75));
        btnAngkaHps.setMinimumSize(new java.awt.Dimension(75, 75));
        btnAngkaHps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngkaHpsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(btnAngkaHps, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        jPanel1.add(jPanel3, gridBagConstraints);

        empty1.setForeground(new java.awt.Color(0, 131, 62));
        empty1.setFocusable(false);
        empty1.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        empty1.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.5;
        jPanel1.add(empty1, gridBagConstraints);

        empty2.setForeground(new java.awt.Color(0, 131, 62));
        empty2.setFocusable(false);
        empty2.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        empty2.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.5;
        jPanel1.add(empty2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCekNoKartuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCekNoKartuKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if (textCekNoKartu.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
                this.setCursor(Cursor.getDefaultCursor());
                return;
            }

            if ((Sequel.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where norm = ? and tanggalperiksa = current_date()", textCekNoKartu.getText()) > 0) ||
                (Sequel.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date()", textCekNoKartu.getText()) > 0)) {
                JOptionPane.showMessageDialog(null, "Pasien telah menggunakan Mobile JKN. Silahkan masuk melalui menu \"Cek In MobileJKN\"..!!");
                this.setCursor(Cursor.getDefaultCursor());
                return;
            }

            if (Sequel.cariIntegerSmc("select count(*) from pasien where no_peserta = ?", textCekNoKartu.getText()) == 1) {
                form.tampilKunjunganPertama(textCekNoKartu.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            } else if (Sequel.cariIntegerSmc("select count(*) from pasien where no_rkm_medis = ?", textCekNoKartu.getText()) == 1) {
                form.tampilKunjunganPertama(Sequel.cariIsiSmc("select no_peserta from pasien where no_rkm_medis = ?", textCekNoKartu.getText()));
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Data pasien tidak ditemukan!");
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_textCekNoKartuKeyPressed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (textCekNoKartu.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }

        if ((Sequel.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where norm = ? and tanggalperiksa = current_date()", textCekNoKartu.getText()) > 0) ||
            (Sequel.cariIntegerSmc("select count(*) from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date()", textCekNoKartu.getText()) > 0)) {
            JOptionPane.showMessageDialog(null, "Pasien telah menggunakan Mobile JKN. Silahkan masuk melalui menu \"Cek In MobileJKN\"..!!");
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }

        if (Sequel.cariIntegerSmc("select count(*) from pasien where no_peserta = ?", textCekNoKartu.getText()) == 1) {
            form.tampilKunjunganPertama(textCekNoKartu.getText());
            form.setSize(this.getWidth(), this.getHeight());
            form.setLocationRelativeTo(jPanel1);
            this.dispose();
            form.setVisible(true);
        } else if (Sequel.cariIntegerSmc("select count(*) from pasien where no_rkm_medis = ?", textCekNoKartu.getText()) == 1) {
            form.tampilKunjunganPertama(Sequel.cariIsiSmc("select no_peserta from pasien where no_rkm_medis = ?", textCekNoKartu.getText()));
            form.setSize(this.getWidth(), this.getHeight());
            form.setLocationRelativeTo(jPanel1);
            this.dispose();
            form.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Data pasien tidak ditemukan!");
        }
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnKonfirmActionPerformed

    private void btnAngka8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka8ActionPerformed
    {//GEN-HEADEREND:event_btnAngka8ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "8");
    }//GEN-LAST:event_btnAngka8ActionPerformed

    private void btnAngka7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka7ActionPerformed
    {//GEN-HEADEREND:event_btnAngka7ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "7");
    }//GEN-LAST:event_btnAngka7ActionPerformed

    private void btnAngka9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka9ActionPerformed
    {//GEN-HEADEREND:event_btnAngka9ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "9");
    }//GEN-LAST:event_btnAngka9ActionPerformed

    private void btnAngka4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka4ActionPerformed
    {//GEN-HEADEREND:event_btnAngka4ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "4");
    }//GEN-LAST:event_btnAngka4ActionPerformed

    private void btnAngka5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka5ActionPerformed
    {//GEN-HEADEREND:event_btnAngka5ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "5");
    }//GEN-LAST:event_btnAngka5ActionPerformed

    private void btnAngka6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka6ActionPerformed
    {//GEN-HEADEREND:event_btnAngka6ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "6");
    }//GEN-LAST:event_btnAngka6ActionPerformed

    private void btnAngka2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka2ActionPerformed
    {//GEN-HEADEREND:event_btnAngka2ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "2");
    }//GEN-LAST:event_btnAngka2ActionPerformed

    private void btnAngka1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka1ActionPerformed
    {//GEN-HEADEREND:event_btnAngka1ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "1");
    }//GEN-LAST:event_btnAngka1ActionPerformed

    private void btnAngka3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka3ActionPerformed
    {//GEN-HEADEREND:event_btnAngka3ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "3");
    }//GEN-LAST:event_btnAngka3ActionPerformed

    private void btnAngka0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngka0ActionPerformed
    {//GEN-HEADEREND:event_btnAngka0ActionPerformed
        textCekNoKartu.setText(textCekNoKartu.getText() + "0");
    }//GEN-LAST:event_btnAngka0ActionPerformed

    private void btnAngkaHpsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAngkaHpsActionPerformed
    {//GEN-HEADEREND:event_btnAngkaHpsActionPerformed
        int length = textCekNoKartu.getText().length();
        int number = textCekNoKartu.getText().length() - 1;
        String store;
        if (length > 0) {
            StringBuilder back = new StringBuilder(textCekNoKartu.getText());
            back.deleteCharAt(number);
            store = back.toString();
            textCekNoKartu.setText(store);
        }
    }//GEN-LAST:event_btnAngkaHpsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearActionPerformed
    {//GEN-HEADEREND:event_btnClearActionPerformed
        int length = textCekNoKartu.getText().length();
        if (length > 0) {
            textCekNoKartu.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCekSEPKunjunganPertama dialog = new DlgCekSEPKunjunganPertama(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private javax.swing.JButton btnAngka0;
    private javax.swing.JButton btnAngka1;
    private javax.swing.JButton btnAngka2;
    private javax.swing.JButton btnAngka3;
    private javax.swing.JButton btnAngka4;
    private javax.swing.JButton btnAngka5;
    private javax.swing.JButton btnAngka6;
    private javax.swing.JButton btnAngka7;
    private javax.swing.JButton btnAngka8;
    private javax.swing.JButton btnAngka9;
    private javax.swing.JButton btnAngkaHps;
    private javax.swing.JButton btnClear;
    private widget.Button btnKonfirm;
    private widget.Button btnTutup;
    private javax.swing.JLabel empty1;
    private javax.swing.JLabel empty2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JTextField textCekNoKartu;
    // End of variables declaration//GEN-END:variables
}
