/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

/**
 *
 * @author Kode
 */
public class DlgAmbilAntrean extends javax.swing.JDialog {

    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private String umur = "0", sttsumur = "Th", jnsloket = "", hurufantrianget = "";
    private String status = "Baru", BASENOREG = "", URUTNOREG = "", aktifjadwal = "";

    private Properties prop = new Properties();
    private int lebar = 0, tinggi = 0, antriansekarang = 0;

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param id
     */
    public DlgAmbilAntrean(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblKdPoli = new component.Label();
        LblKdDokter = new component.Label();
        NoReg = new component.TextBox();
        NoRawat = new component.TextBox();
        Biaya = new component.TextBox();
        jPanel1 = new component.Panel();
        jPanel2 = new javax.swing.JPanel();
        lblNamaAntrian = new component.Label();
        jPanel3 = new javax.swing.JPanel();
        lblNoAntrian = new component.Label();
        buttonBig1 = new widget.ButtonBig();
        buttonBig2 = new widget.ButtonBig();
        buttonBig3 = new widget.ButtonBig();
        buttonBig4 = new widget.ButtonBig();
        buttonBig5 = new widget.ButtonBig();
        buttonBig6 = new widget.ButtonBig();
        jPanel4 = new javax.swing.JPanel();
        BtnClose3 = new widget.ButtonBig();

        LblKdPoli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdPoli.setText("Norm");
        LblKdPoli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdPoli.setPreferredSize(new java.awt.Dimension(20, 14));

        LblKdDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblKdDokter.setText("Norm");
        LblKdDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblKdDokter.setPreferredSize(new java.awt.Dimension(20, 14));

        NoReg.setPreferredSize(new java.awt.Dimension(320, 30));
        NoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRegActionPerformed(evt);
            }
        });
        NoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRegKeyPressed(evt);
            }
        });

        NoRawat.setPreferredSize(new java.awt.Dimension(320, 30));
        NoRawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRawatActionPerformed(evt);
            }
        });
        NoRawat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRawatKeyPressed(evt);
            }
        });

        Biaya.setPreferredSize(new java.awt.Dimension(320, 30));
        Biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiayaActionPerformed(evt);
            }
        });
        Biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BiayaKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 131, 62)));
        jPanel1.setForeground(new java.awt.Color(0, 131, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 60));

        lblNamaAntrian.setForeground(new java.awt.Color(0, 131, 62));
        lblNamaAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaAntrian.setText("AMBIL ANTRIAN");
        lblNamaAntrian.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblNamaAntrian.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        lblNamaAntrian.setPreferredSize(new java.awt.Dimension(500, 75));
        jPanel2.add(lblNamaAntrian);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setForeground(new java.awt.Color(238, 238, 255));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWeights = new double[] {1.0, 1.0, 5.0};
        jPanel3Layout.rowWeights = new double[] {1.0, 1.0, 1.0, 1.0, 1.0, 1.0};
        jPanel3.setLayout(jPanel3Layout);

        lblNoAntrian.setForeground(new java.awt.Color(0, 131, 62));
        lblNoAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoAntrian.setText("F0001");
        lblNoAntrian.setFont(new java.awt.Font("Inter", 1, 48)); // NOI18N
        lblNoAntrian.setIconTextGap(0);
        lblNoAntrian.setPreferredSize(new java.awt.Dimension(350, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel3.add(lblNoAntrian, gridBagConstraints);

        buttonBig1.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig1.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig1.setText("ANTRIAN A");
        buttonBig1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig1, gridBagConstraints);

        buttonBig2.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig2.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig2.setText("ANTRIAN B");
        buttonBig2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig2, gridBagConstraints);

        buttonBig3.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig3.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig3.setText("ANTRIAN C");
        buttonBig3.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig3, gridBagConstraints);

        buttonBig4.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig4.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig4.setText("ANTRIAN D");
        buttonBig4.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig4, gridBagConstraints);

        buttonBig5.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig5.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig5.setText("ANTRIAN E");
        buttonBig5.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig5, gridBagConstraints);

        buttonBig6.setBackground(new java.awt.Color(0, 131, 62));
        buttonBig6.setForeground(new java.awt.Color(50, 50, 50));
        buttonBig6.setText("ANTRIAN F");
        buttonBig6.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(buttonBig6, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(238, 238, 255));
        jPanel4.setForeground(new java.awt.Color(238, 238, 255));

        BtnClose3.setBackground(new java.awt.Color(255, 255, 255));
        BtnClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnClose3.setMnemonic('U');
        BtnClose3.setText("Batal");
        BtnClose3.setToolTipText("Alt+U");
        BtnClose3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        BtnClose3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnClose3.setIconTextGap(0);
        BtnClose3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnClose3.setPreferredSize(new java.awt.Dimension(250, 75));
        BtnClose3.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClose3ActionPerformed(evt);
            }
        });
        jPanel4.add(BtnClose3);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void NoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegActionPerformed

    private void NoRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRegKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegKeyPressed

    private void NoRawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatActionPerformed

    private void NoRawatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRawatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRawatKeyPressed

    private void BiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaActionPerformed

    private void BiayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BiayaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaKeyPressed

    private void BtnClose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClose3ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnClose3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgAmbilAntrean dialog = new DlgAmbilAntrean(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.TextBox Biaya;
    private widget.ButtonBig BtnClose3;
    private component.Label LblKdDokter;
    private component.Label LblKdPoli;
    private component.TextBox NoRawat;
    private component.TextBox NoReg;
    private widget.ButtonBig buttonBig1;
    private widget.ButtonBig buttonBig2;
    private widget.ButtonBig buttonBig3;
    private widget.ButtonBig buttonBig4;
    private widget.ButtonBig buttonBig5;
    private widget.ButtonBig buttonBig6;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private component.Label lblNamaAntrian;
    private component.Label lblNoAntrian;
    // End of variables declaration//GEN-END:variables

    public void setPasien(String norm, String kodepoli, String kddokter) {
    }

    public void setNoAntrian(String namalabel, String hurufantrian, String tipeloket) {
        jnsloket = "";
        if (Sequel.cariInteger("select count(antrian_loket.noantrian) from antrian_loket where round(DATE_FORMAT(postdate, '%d')) = DAY(CURDATE()) AND round(DATE_FORMAT(postdate, '%m')) = MONTH(CURDATE()) AND round(DATE_FORMAT(postdate, '%Y')) = YEAR(CURDATE()) AND type = '" + tipeloket + "'") < 1) {
            antriansekarang = 1;
        } else {
            antriansekarang = Integer.parseInt(Sequel.cariIsi("SELECT MAX(CAST(noantrian as UNSIGNED)) as noantrian FROM antrian_loket WHERE round(DATE_FORMAT(postdate, '%d')) = DAY(CURDATE()) AND round(DATE_FORMAT(postdate, '%m')) = MONTH(CURDATE()) AND round(DATE_FORMAT(postdate, '%Y')) = YEAR(CURDATE()) AND type = '" + tipeloket + "' ORDER BY round(noantrian) DESC")) + 1;
        }

        lblNoAntrian.setText(hurufantrian + "" + antriansekarang);
        lblNamaAntrian.setText(namalabel);
        jnsloket = tipeloket;
        hurufantrianget = hurufantrian;

    }

    private void CetakAntrian(String label, Integer noantrian, String tgl, String jam) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        Map<String, Object> param = new HashMap<>();
        param.put("labelantrian", label);
        param.put("nomorantrian", hurufantrianget + String.valueOf(noantrian));
        param.put("tanggal", tgl);
        param.put("jam", jam);
        param.put("namars", Sequel.cariIsi("select nama_instansi from setting"));
        param.put("alamatrs", Sequel.cariIsi("select alamat_instansi from setting"));
        param.put("kotars", Sequel.cariIsi("select kabupaten from setting"));
        param.put("propinsirs", Sequel.cariIsi("select propinsi from setting"));
        param.put("kontakrs", Sequel.cariIsi("select kontak from setting"));
        param.put("emailrs", Sequel.cariIsi("select email from setting"));
        param.put("logo", Sequel.cariGambar("select logo from setting"));

        Valid.MyReportqryabdulAntrian("rptAntrianLoket.jasper", "report", "::[ No Antrian Loket ]::",
                "", param);

        this.setCursor(Cursor.getDefaultCursor());

    }
}
