/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;

public class DlgAmbilAntrianFarmasi extends widget.Dialog {

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();

    private Map<String, Object> param = new HashMap<>();

    public DlgAmbilAntrianFarmasi(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();

        try (ResultSet rs = koneksi.createStatement().executeQuery(
            "select nama_instansi, alamat_instansi, kabupaten, propinsi, kontak, email from setting"
        )) {
            if (rs.next()) {
                param.put("namars", rs.getString("nama_instansi"));
                param.put("alamatrs", rs.getString("alamat_instansi"));
                param.put("kotars", rs.getString("kabupaten"));
                param.put("propinsirs", rs.getString("propinsi"));
                param.put("kontakrs", rs.getString("kontak"));
                param.put("emailrs", rs.getString("email"));
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new widget.Panel();
        judul = new widget.Label();
        panelTengah = new widget.Panel();
        HurufF = new widget.MenuButton();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelAtas.setPreferredSize(new java.awt.Dimension(60, 60));

        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("AMBIL ANTRIAN");
        judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        judul.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(500, 75));
        panelAtas.add(judul);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setLayout(new java.awt.GridLayout(0, 2));

        HurufF.setText("ANTRIAN F");
        HurufF.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        HurufF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HurufFActionPerformed(evt);
            }
        });
        panelTengah.add(HurufF);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        btnKeluar.setBackground(new java.awt.Color(240, 249, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 33, 32));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setMnemonic('U');
        btnKeluar.setText("KELUAR");
        btnKeluar.setToolTipText("Alt+U");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnKeluar.setIconTextGap(2);
        btnKeluar.setPreferredSize(new java.awt.Dimension(200, 75));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HurufFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HurufFActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        cetakAntrianHuruf("F");
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_HurufFActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampil();
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.MenuButton HurufF;
    private widget.Button btnKeluar;
    private widget.Label judul;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    private void cetakAntrianHuruf(String prefix) {
        if (Sequel.executeRawSmc(
            "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('F', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
            String.valueOf(Integer.parseInt(HurufF.getText().substring(HurufF.getText().indexOf("(") + 2, HurufF.getText().length() - 1)) + 1)
        )) {
            param.put("logo", Sequel.cariGambar("select logo from setting"));
            Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 2,
                "select date_format(tanggal, '%d-%m-%Y') as tanggal, nomor, jam from " +
                "antriloketcetak_smc where left(nomor, 1) = 'F' and tanggal = current_date() order by nomor desc limit 1");
        }
        tampil();
    }

    private void tampil() {
        HurufF.setText("ANTRIAN F (" + Sequel.cariIsiSmc("select ifnull(max(nomor), 'F000') from antriloketcetak_smc where tanggal = current_date() and left(nomor, 1) = 'F'") + ")");
    }
}
