package khanzahmsanjungan;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class DlgCekSKDPKontrol extends javax.swing.JDialog {
    private final sekuel Sequel = new sekuel();
    private final DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);

    public DlgCekSKDPKontrol(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new javax.swing.JPanel();
        NoRMPasien = new widget.TextBox();
        jLabel28 = new widget.Label();
        BtnBatal = new widget.Button();
        BtnKonfirm = new widget.Button();
        panelNumpad1 = new widget.PanelNumpad();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(413, 115));
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/bpjs-amiz.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 255)), "::[ Cek Data Rencana Kontrol ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 131, 62));
        jPanel1.setMinimumSize(new java.awt.Dimension(413, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(413, 115));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(NoRMPasien, gridBagConstraints);

        jLabel28.setForeground(new java.awt.Color(0, 131, 62));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("No. Surat Kontrol :");
        jLabel28.setFont(new java.awt.Font("Inter Medium", 0, 36)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel28, gridBagConstraints);

        BtnBatal.setBackground(new java.awt.Color(255, 255, 255));
        BtnBatal.setForeground(new java.awt.Color(255, 33, 32));
        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnBatal.setMnemonic('U');
        BtnBatal.setText("BATAL");
        BtnBatal.setToolTipText("Alt+U");
        BtnBatal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnBatal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBatal.setIconTextGap(2);
        BtnBatal.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(BtnBatal, gridBagConstraints);

        BtnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnKonfirm.setMnemonic('U');
        BtnKonfirm.setText("CEK");
        BtnKonfirm.setToolTipText("Alt+U");
        BtnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKonfirm.setIconTextGap(0);
        BtnKonfirm.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setVerifyInputWhenFocusTarget(false);
        BtnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(BtnKonfirm, gridBagConstraints);

        panelNumpad1.setSkdpMode(true);
        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(panelNumpad1, gridBagConstraints);

        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel6, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cek();
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmActionPerformed
        cek();
    }//GEN-LAST:event_BtnKonfirmActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnKonfirm;
    private widget.TextBox NoRMPasien;
    private usu.widget.glass.PanelGlass PanelWall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private widget.Label jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private widget.PanelNumpad panelNumpad1;
    // End of variables declaration//GEN-END:variables

    private void cek() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
            formWindowActivated(null);
        } else {
            String noSKDP = Sequel.cariIsiSmc(
                "select bridging_surat_kontrol_bpjs.no_surat from bridging_surat_kontrol_bpjs where " +
                "bridging_surat_kontrol_bpjs.no_surat = ?", NoRMPasien.getText().trim()
            );
            if (noSKDP.isBlank()) {
                JOptionPane.showMessageDialog(null, "Data Jadwal Rencana Kontrol tidak ditemukan..!!");
                formWindowActivated(null);
            } else {
                if (Sequel.cariExistsSmc("select * from referensi_mobilejkn_bpjs where nomorreferensi = ? and tanggalperiksa = current_date() and status = 'Belum'", noSKDP)) {
                    JOptionPane.showMessageDialog(null, "Pasien telah mendaftar online menggunakan MobileJKN.\nSilahkan cekin di menu \"Cek In MobileJKN\"..!!");
                    formWindowActivated(null);
                } else if (Sequel.cariIntegerSmc("select datediff((select tgl_rencana from bridging_surat_kontrol_bpjs where no_surat = ?), current_date())", noSKDP) > 0) {
                    JOptionPane.showMessageDialog(null, "Jadwal kontrol pasien tidak boleh dimajukan..!!");
                    formWindowActivated(null);
                } else {
                    form.tampilKontrol(noSKDP);
                    form.setSize(this.getWidth(), this.getHeight());
                    form.setLocationRelativeTo(jPanel1);
                    this.dispose();
                    form.setVisible(true);
                }
            }
            formWindowActivated(null);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }
}
