package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public final class DlgCariJadwal extends widget.Dialog {

    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private String harikerja = "";

    public DlgCariJadwal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Object[] row = {"Hari", "Poliklinik", "Dokter Spesialis", "Jam Praktek", "Kuota", "kdpoli", "kddokter", "kdpolibpjs", "kddokterbpjs"};
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbPoli.setModel(tabMode);

        for (int i = 0; i < row.length; i++) {
            TableColumn column = tbPoli.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(100);
            } else if (i == 1) {
                column.setPreferredWidth(400);
            } else if (i == 2) {
                column.setPreferredWidth(600);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(90);
            } else {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new widget.ScrollPane();
        tbPoli = new widget.Table();
        panelBawah = new widget.Panel();
        btnKeluar = new widget.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N

        tbPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbPoliMouseReleased(evt);
            }
        });
        Scroll.setViewportView(tbPoli);

        getContentPane().add(Scroll, java.awt.BorderLayout.CENTER);

        panelBawah.setName("panelBawah"); // NOI18N
        panelBawah.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setForeground(new java.awt.Color(255, 23, 26));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select jadwal.hari_kerja, maping_poli_bpjs.nm_poli_bpjs, maping_dokter_dpjpvclaim.nm_dokter_bpjs, " +
            "concat(left(jadwal.jam_mulai, 5), '-', left(jadwal.jam_selesai, 5)) as jampraktek, jadwal.kuota, " +
            "jadwal.kd_poli, jadwal.kd_dokter, maping_poli_bpjs.kd_poli_bpjs, maping_dokter_dpjpvclaim.kd_dokter_bpjs " +
            "from jadwal join maping_dokter_dpjpvclaim on jadwal.kd_dokter = maping_dokter_dpjpvclaim.kd_dokter join " +
            "maping_poli_bpjs on jadwal.kd_poli = maping_poli_bpjs.kd_poli_rs where jadwal.hari_kerja = ? order by " +
            "jadwal.hari_kerja, maping_poli_bpjs.nm_poli_bpjs, jadwal.jam_mulai, maping_dokter_dpjpvclaim.nm_dokter_bpjs"
        )) {
            ps.setString(1, harikerja);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {
                        rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5),
                        rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbPoliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPoliMouseReleased
        dispose();
    }//GEN-LAST:event_tbPoliMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button btnKeluar;
    private widget.Panel panelBawah;
    private widget.Table tbPoli;
    // End of variables declaration//GEN-END:variables

    public void setHarikerja(String harikerja) {
        this.harikerja = harikerja;
    }
    
    public boolean hasSelectedRow() {
        return tbPoli.getSelectedRow() >= 0;
    }
    
    public Object getSelectedRow(int column) {
        return tbPoli.getValueAt(tbPoli.getSelectedRow(), column);
    }
}
