package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class DlgCekinBooking extends widget.Dialog {

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final String KODEPOLIEKSEKUTIF = koneksiDB.KODEPOLIEKSEKUTIF();

    public DlgCekinBooking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        PanelWall = new usu.widget.glass.PanelGlass();
        panelTengah = new widget.Panel();
        NoRMPasien = new widget.TextField();
        jLabel28 = new widget.Label();
        BtnClose = new widget.Button();
        BtnKonfirm = new widget.Button();
        panelNumpad1 = new widget.Numpad();
        jLabel1 = new widget.Label();
        jLabel2 = new widget.Label();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelAtas.add(PanelWall);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::[ Cek In Booking Registrasi ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        panelTengah.setPreferredSize(new java.awt.Dimension(400, 70));
        panelTengah.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelTengah.add(NoRMPasien, gridBagConstraints);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setLabelFor(NoRMPasien);
        jLabel28.setText("No. RM / NIK :");
        jLabel28.setFont(new java.awt.Font("Inter Medium", 0, 36)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel28, gridBagConstraints);

        BtnClose.setBackground(new java.awt.Color(255, 255, 255));
        BtnClose.setForeground(new java.awt.Color(255, 33, 32));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnClose.setMnemonic('U');
        BtnClose.setText("BATAL");
        BtnClose.setToolTipText("Alt+U");
        BtnClose.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnClose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnClose.setIconTextGap(2);
        BtnClose.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelTengah.add(BtnClose, gridBagConstraints);

        BtnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnKonfirm.setMnemonic('U');
        BtnKonfirm.setText("CEK");
        BtnKonfirm.setToolTipText("Alt+U");
        BtnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKonfirm.setIconTextGap(0);
        BtnKonfirm.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setVerifyInputWhenFocusTarget(false);
        BtnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(BtnKonfirm, gridBagConstraints);

        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(panelNumpad1, gridBagConstraints);

        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel1, gridBagConstraints);

        jLabel2.setEnabled(false);
        jLabel2.setFocusable(false);
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel2, gridBagConstraints);

        jLabel3.setEnabled(false);
        jLabel3.setFocusable(false);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel3, gridBagConstraints);

        jLabel4.setEnabled(false);
        jLabel4.setFocusable(false);
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel4, gridBagConstraints);

        jLabel5.setEnabled(false);
        jLabel5.setFocusable(false);
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel5, gridBagConstraints);

        jLabel6.setEnabled(false);
        jLabel6.setFocusable(false);
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel6, gridBagConstraints);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmActionPerformed
        cek();
    }//GEN-LAST:event_BtnKonfirmActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cek();
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnClose;
    private widget.Button BtnKonfirm;
    private widget.TextField NoRMPasien;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.Label jLabel1;
    private widget.Label jLabel2;
    private widget.Label jLabel28;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Panel panelAtas;
    private widget.Numpad panelNumpad1;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    private void cek() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
        } else {
            String noRM = Sequel.cariIsiSmc("select pasien.no_rkm_medis from pasien where pasien.no_rkm_medis = ? or pasien.no_ktp = ?", NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
            if (noRM.isBlank()) {
                JOptionPane.showMessageDialog(null, "Maaf, data pasien tidak ditemukan\nSilahkan konfirmasi ke pendaftaran..!!");
            } else {
                try (PreparedStatement ps = koneksi.prepareStatement(
                    "select b.no_rawat, b.status, r.stts, exists(select * from pemeriksaan_ralan as p where p.no_rawat = b.no_rawat) as ada_pemeriksaan from " +
                    "booking_registrasi as b join reg_periksa as r on b.no_rawat = r.no_rawat where b.no_rkm_medis = ? and b.tanggal_periksa = current_date() " +
                    (KODEPOLIEKSEKUTIF.isBlank() ? "" : "and b.kd_poli = ?")
                )) {
                    ps.setString(1, noRM);
                    if (!KODEPOLIEKSEKUTIF.isBlank()) {
                        ps.setString(2, KODEPOLIEKSEKUTIF);
                    }
                    try (ResultSet rs = ps.executeQuery()) {
                        if (rs.first()) {
                            Map<String, Object> param = new HashMap<>();
                            param.put("norawat", rs.getString("no_rawat"));
                            param.put("namars", Sequel.cariIsiSmc("select setting.nama_instansi from setting limit 1"));
                            param.put("kotars", Sequel.cariIsiSmc("select setting.kabupaten from setting limit 1"));
                            if (!rs.getString("stts").equals("Belum") || rs.getBoolean("ada_pemeriksaan")) {
                                JOptionPane.showMessageDialog(null, "Anda sudah menerima pelayanan pada hari ini..!!\nSilahkan konfirmasi ke petugas.", "Gagal", JOptionPane.ERROR_MESSAGE);
                            } else if (rs.getString("status").equals("Checkin")) {
                                if (JOptionPane.showConfirmDialog(null, "Anda sudah melakukan checkin pada hari ini\nApakah mau mencetak barcode?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                                    Valid.printReport("rptBarcodeRawatAPM.jasper", koneksiDB.PRINTER_BARCODE(), "::[ Barcode Perawatan ]::", koneksiDB.PRINTJUMLAHBARCODE(), param);
                                    JOptionPane.showMessageDialog(null, "Barcode berhasil dicetak..!!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                                }
                            } else {
                                Sequel.mengupdateSmc("reg_periksa", "jam_reg = current_time()", "no_rawat = ?", rs.getString("no_rawat"));
                                Sequel.mengupdateSmc("booking_registrasi", "waktu_kunjungan = now(), status = 'Checkin'", "no_rawat = ?", rs.getString("no_rawat"));
                                JOptionPane.showMessageDialog(null, "Check in berhasil..!!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                                Valid.printReport("rptBarcodeRawatAPM.jasper", koneksiDB.PRINTER_BARCODE(), "::[ Barcode Perawatan ]::", koneksiDB.PRINTJUMLAHBARCODE(), param);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Maaf, jadwal booking untuk hari ini tidak ditemukan\nSilahkan konfirmasi ke pendaftaran..!!");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("Notif : " + e);
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada saat mencari data pasien\nSilahkan hubungi administrator..!!");
                }
            }
        }
        formWindowActivated(null);
        this.setCursor(Cursor.getDefaultCursor());
    }
}
