package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class DlgCekBooking extends javax.swing.JDialog {

    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final String KODEPOLIEKSEKUTIF = koneksiDB.KODEPOLIEKSEKUTIF();

    public DlgCekBooking(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
        
        NoRMPasien.setDocument(new PlainDocument() {
            @Override
            public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                if (str == null) return;
                if (getLength() + str.length() <= panelNumpad1.getTextLimit()) {
                    super.insertString(offs, str, a);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        panelUtama = new javax.swing.JPanel();
        NoRMPasien = new widget.TextBox();
        jLabel28 = new widget.Label();
        BtnClose = new widget.Button();
        BtnClose2 = new widget.Button();
        panelNumpad1 = new widget.PanelNumpad();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        panelHeader.setBackground(new java.awt.Color(238, 238, 255));
        panelHeader.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelHeader.add(PanelWall);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelUtama.setBackground(new java.awt.Color(238, 238, 255));
        panelUtama.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 255)), "::[ Cek Booking Registrasi ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        panelUtama.setForeground(new java.awt.Color(0, 131, 62));
        panelUtama.setPreferredSize(new java.awt.Dimension(400, 70));
        panelUtama.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelUtama.add(NoRMPasien, gridBagConstraints);

        jLabel28.setForeground(new java.awt.Color(0, 131, 62));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setLabelFor(NoRMPasien);
        jLabel28.setText("No. RM / NIK :");
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel28, gridBagConstraints);

        BtnClose.setBackground(new java.awt.Color(255, 255, 255));
        BtnClose.setForeground(new java.awt.Color(255, 33, 32));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnClose.setMnemonic('U');
        BtnClose.setText("BATAL");
        BtnClose.setToolTipText("Alt+U");
        BtnClose.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnClose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnClose.setIconTextGap(2);
        BtnClose.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelUtama.add(BtnClose, gridBagConstraints);

        BtnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnClose2.setMnemonic('U');
        BtnClose2.setText("CEK");
        BtnClose2.setToolTipText("Alt+U");
        BtnClose2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnClose2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnClose2.setIconTextGap(0);
        BtnClose2.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnClose2.setVerifyInputWhenFocusTarget(false);
        BtnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClose2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(BtnClose2, gridBagConstraints);

        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(panelNumpad1, gridBagConstraints);

        jLabel1.setEnabled(false);
        jLabel1.setFocusable(false);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel1, gridBagConstraints);

        jLabel2.setEnabled(false);
        jLabel2.setFocusable(false);
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel2, gridBagConstraints);

        jLabel3.setEnabled(false);
        jLabel3.setFocusable(false);
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel3, gridBagConstraints);

        jLabel4.setEnabled(false);
        jLabel4.setFocusable(false);
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel4, gridBagConstraints);

        jLabel5.setEnabled(false);
        jLabel5.setFocusable(false);
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel5, gridBagConstraints);

        jLabel6.setEnabled(false);
        jLabel6.setFocusable(false);
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelUtama.add(jLabel6, gridBagConstraints);

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClose2ActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        cekBooking();
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnClose2ActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            cekBooking();
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnClose;
    private widget.Button BtnClose2;
    private widget.TextBox NoRMPasien;
    private usu.widget.glass.PanelGlass PanelWall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private widget.Label jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelHeader;
    private widget.PanelNumpad panelNumpad1;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables

    private void cekBooking() {
        if (NoRMPasien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
            return;
        }
        
        String noRM = Sequel.cariIsiSmc("select pasien.no_rkm_medis from pasien where pasien.no_rkm_medis = ? or pasien.no_ktp = ?", NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
        if (noRM.isBlank()) {
            JOptionPane.showMessageDialog(null, "Maaf, data pasien tidak ditemukan\nSilahkan konfirmasi ke pendaftaran..!!");
            formWindowActivated(null);
            return;
        }
        
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select reg_periksa.no_rawat, reg_periksa.tgl_registrasi, reg_periksa.no_rkm_medis, " +
            "reg_periksa.kd_dokter, reg_periksa.kd_poli, reg_periksa.kd_pj from reg_periksa where " +
            "reg_periksa.no_rkm_medis = ? and reg_periksa.tgl_registrasi = current_date() and " +
            "reg_periksa.stts = 'Belum' and exists(select * from booking_registrasi where " +
            "booking_registrasi.no_rawat = reg_periksa.no_rawat and booking_registrasi.status = 'Belum')" +
            (KODEPOLIEKSEKUTIF.isBlank() ? "" : " and reg_periksa.kd_poli = ?")
        )) {
            ps.setString(1, noRM);
            if (!KODEPOLIEKSEKUTIF.isBlank()) {
                ps.setString(2, KODEPOLIEKSEKUTIF);
            }
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.first()) {
                    Sequel.mengupdateSmc("reg_periksa", "jam_reg = current_time()", "no_rawat = ?", rs.getString("no_rawat"));
                    Sequel.mengupdateSmc("booking_registrasi", "waktu_kunjungan = now(), status = 'Checkin'", "no_rawat = ?", rs.getString("no_rawat"));
                    JOptionPane.showMessageDialog(null, "Check in berhasil..!!");
                    Map<String, Object> param = new HashMap<>();
                    param.put("norawat", rs.getString("no_rawat"));
                    param.put("namars", Sequel.cariIsiSmc("select setting.nama_instansi from setting limit 1"));
                    param.put("kotars", Sequel.cariIsiSmc("select setting.kabupaten from setting limit 1"));
                    Valid.printReport("rptBarcodeRawatAPM.jasper", koneksiDB.PRINTER_BARCODE(), "::[ Barcode Perawatan ]::", koneksiDB.PRINTJUMLAHBARCODE(), param);
                    formWindowActivated(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf, jadwal booking untuk hari ini tidak ditemukan\nSilahkan konfirmasi ke pendaftaran..!!");
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada saat mencari data pasien\nSilahkan hubungi administrator..!!");
        }
    }
}
