/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */
package khanzahmsanjungan;

import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public final class DlgCariPoli extends javax.swing.JDialog {

    private final DefaultTableModel tabMode;
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private final ObjectMapper mapper = new ObjectMapper();
    private boolean tampilBPJS = false;

    public DlgCariPoli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10, 2);
        setSize(656, 250);

        Object[] row = {"Kode Unit", "Nama Unit", "registrasi", "registrasilama", "kddokterbpjs", "nmdokterbpjs"};
        tabMode = new DefaultTableModel(null, row) {
            Class[] type = new Class[] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class,
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return type[columnIndex];
            }
        };
        tbKamar.setModel(tabMode);
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 6; i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if (i == 0) {
                if (tampilBPJS) {
                    column.setMinWidth(0);
                    column.setMaxWidth(0);
                } else {
                    column.setPreferredWidth(150);
                }
            } else if (i == 1) {
                if (tampilBPJS) {
                    column.setMinWidth(0);
                    column.setMaxWidth(0);
                } else {
                    column.setPreferredWidth(500);
                }
            } else if (i == 2) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 3) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 4) {
                if (tampilBPJS) {
                    column.setPreferredWidth(150);
                } else {
                    column.setMinWidth(0);
                    column.setMaxWidth(0);
                }
            } else if (i == 5) {
                if (tampilBPJS) {
                    column.setPreferredWidth(500);
                } else {
                    column.setMinWidth(0);
                    column.setMaxWidth(0);
                }
            }
        }
            }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        jPanel1 = new javax.swing.JPanel();
        button1 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(null);
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setBackground(new java.awt.Color(238, 238, 255));
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setBackground(new java.awt.Color(238, 238, 255));
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setForeground(new java.awt.Color(0, 131, 62));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        button1.setBackground(new java.awt.Color(238, 238, 255));
        button1.setForeground(new java.awt.Color(0, 131, 62));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        button1.setText("KELUAR");
        button1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        button1.setName("button1"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);

        internalFrame1.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if (tabMode.getRowCount() != 0) {
            if (evt.getClickCount() == 1) {
                dispose();
            }
        }
}//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed

    }//GEN-LAST:event_tbKamarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ScrollPane Scroll;
    private widget.Button button1;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JPanel jPanel1;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables
    
    public void tampil(String hariKerja) {
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select poliklinik.kd_poli, poliklinik.nm_poli, poliklinik.registrasi, poliklinik.registrasilama, " +
            "maping_poli_bpjs.kd_poli_bpjs, maping_poli_bpjs.nm_poli_bpjs from poliklinik left join " +
            "maping_poli_bpjs on poliklinik.kd_poli = maping_poli_bpjs.kd_poli_rs where poliklinik.status = '1' " +
            "and exists(select * from jadwal where jadwal.kd_poli = poliklinik.kd_poli and jadwal.hari_kerja = ?) " +
            "order by field(poliklinik.kd_poli, 'U0038') = 0, poliklinik.nm_poli"
        )) {
            ps.setString(1, hariKerja);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    do {
                        tabMode.addRow(new Object[] {
                            rs.getString("kd_poli"), rs.getString("nm_poli"), rs.getDouble("registrasi"),
                            rs.getDouble("registrasilama"), rs.getString("kd_poli_bpjs"), rs.getString("nm_poli_bpjs")
                        });
                    } while (rs.next());
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public void tampilPoliMapping(String kodepolihfis) {
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select poliklinik.kd_poli, poliklinik.nm_poli from poliklinik where exists(select * from " +
            "maping_poli_bpjs where maping_poli_bpjs.kd_poli_rs = poliklinik.kd_poli and maping_poli_bpjs.kd_poli_bpjs = ?)"
        )) {
            ps.setString(1, kodepolihfis);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    do {
                        tabMode.addRow(new Object[] {rs.getString(1), rs.getString(2), 0, 0, "", ""});
                    } while (rs.next());
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    public JTable getTable() {
        return tbKamar;
    }
}
