package khanzahmsanjungan;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

public class DlgCekDataBPJS extends widget.Dialog {

    public static final int SEP_KUNJUNGAN_PERTAMA = 1;
    public static final int SEP_KONTROL = 2;
    public static final int SEP_KONTROL_BEDA_POLI = 3;
    public static final int SEP_MOBILEJKN = 4;
    
    private static final String TITLE_SEP_KUNJUNGAN_PERTAMA = "::[ Pendaftaran SEP Kunjungan Pertama ]::";
    private static final String TITLE_SEP_KONTROL = "::[ Pendaftaran SEP Kontrol ]::";
    private static final String TITLE_SEP_KONTROL_BEDA_POLI = "::[ Pendaftaran SEP Kontrol Beda Poli ]::";
    private static final String TITLE_SEP_MOBILEJKN = "::[ Cek in Booking MobileJKN ]::";
    private static final String INPUT_RM = "No. RM / NIK / Peserta BPJS :";
    private static final String INPUT_KONTROL = "No. Surat Kontrol :";
    private static final String INPUT_MOBILEJKN = "No. RM / NIK / Peserta BPJS / Surat Kontrol :";
    
    private final sekuel Sequel = new sekuel();
    private final DlgRegistrasiBPJS regist;
    
    private int flag = -1;

    public DlgCekDataBPJS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        regist = new DlgRegistrasiBPJS(parent, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        PanelWall = new usu.widget.glass.PanelGlass();
        panelTengah = new widget.Panel();
        NoRMPasien = new widget.TextField();
        labelInput = new widget.Label();
        BtnBatal = new widget.Button();
        BtnKonfirm = new widget.Button();
        panelNumpad1 = new widget.Numpad();
        jLabel1 = new widget.Label();
        jLabel2 = new widget.Label();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/bpjs-amiz.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelAtas.add(PanelWall);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), " ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        panelTengah.setPreferredSize(new java.awt.Dimension(400, 70));
        panelTengah.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelTengah.add(NoRMPasien, gridBagConstraints);

        labelInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInput.setText("No. RM / NIK / Peserta BPJS :");
        labelInput.setFont(new java.awt.Font("Inter Medium", 0, 36)); // NOI18N
        labelInput.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(labelInput, gridBagConstraints);

        BtnBatal.setBackground(new java.awt.Color(255, 255, 255));
        BtnBatal.setForeground(new java.awt.Color(255, 33, 32));
        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnBatal.setMnemonic('U');
        BtnBatal.setText("BATAL");
        BtnBatal.setToolTipText("Alt+U");
        BtnBatal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnBatal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBatal.setIconTextGap(2);
        BtnBatal.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelTengah.add(BtnBatal, gridBagConstraints);

        BtnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnKonfirm.setMnemonic('U');
        BtnKonfirm.setText("CEK");
        BtnKonfirm.setToolTipText("Alt+U");
        BtnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKonfirm.setIconTextGap(0);
        BtnKonfirm.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setVerifyInputWhenFocusTarget(false);
        BtnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(BtnKonfirm, gridBagConstraints);

        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(panelNumpad1, gridBagConstraints);

        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel1, gridBagConstraints);

        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel2, gridBagConstraints);

        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel3, gridBagConstraints);

        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel4, gridBagConstraints);

        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel5, gridBagConstraints);

        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel6, gridBagConstraints);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmActionPerformed
        cek();
    }//GEN-LAST:event_BtnKonfirmActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cek();
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnKonfirm;
    private widget.TextField NoRMPasien;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.Label jLabel1;
    private widget.Label jLabel2;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label labelInput;
    private widget.Panel panelAtas;
    private widget.Numpad panelNumpad1;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    public void setFlag(int flag) {
        if (flag <= 0) {
            JOptionPane.showMessageDialog(null, "Flag tidak valid..!!");
            return;
        }
        
        this.flag = flag;
        panelNumpad1.setSkdpMode(flag == SEP_KONTROL || flag == SEP_MOBILEJKN);
        TitledBorder border = (TitledBorder) panelTengah.getBorder();
        
        switch (flag) {
            case SEP_KUNJUNGAN_PERTAMA:
                border.setTitle(TITLE_SEP_KUNJUNGAN_PERTAMA);
                labelInput.setText(INPUT_RM);
                break;
            case SEP_KONTROL:
                border.setTitle(TITLE_SEP_KONTROL);
                labelInput.setText(INPUT_KONTROL);
                break;
            case SEP_KONTROL_BEDA_POLI:
                border.setTitle(TITLE_SEP_KONTROL_BEDA_POLI);
                labelInput.setText(INPUT_RM);
                break;
            case SEP_MOBILEJKN:
                border.setTitle(TITLE_SEP_MOBILEJKN);
                labelInput.setText(INPUT_MOBILEJKN);
                break;
            default:
                border.setTitle(TITLE_SEP_KUNJUNGAN_PERTAMA);
                labelInput.setText(INPUT_RM);
                break;
        }
        repaint();
    }
    
    private void cek() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
        } else {
            if (flag == SEP_MOBILEJKN) {
                String noKartu = Sequel.cariIsiSmc("select pasien.no_peserta from pasien where (pasien.no_ktp = ? or pasien.no_peserta = ? or pasien.no_rkm_medis = ?)", NoRMPasien.getText().trim(), NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
                if (noKartu.isBlank()) {
                    noKartu = Sequel.cariIsiSmc("select bridging_sep.no_kartu from bridging_surat_kontrol_bpjs join bridging_sep on bridging_surat_kontrol_bpjs.no_sep = bridging_sep.no_sep where bridging_surat_kontrol_bpjs.no_surat = ?", NoRMPasien.getText().trim());
                }
                if (noKartu.isBlank()) {
                    JOptionPane.showMessageDialog(null, "Data pasien tidak ditemukan..!!");
                } else {
                    if (Sequel.cariExistsSmc("select * from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date() and status in ('Belum', 'Checkin')", noKartu)) {
                        regist.tampilMobileJKN(noKartu);
                        regist.setSize(getContentPane().getSize());
                        regist.setLocationRelativeTo(getContentPane());
                        regist.setVisible(true);
                        this.flag = -1;
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data booking MobileJKN tidak ditemukan..!!");
                    }
                }
            } else if (flag == SEP_KONTROL) {
                String noSKDP = Sequel.cariIsiSmc("select bridging_surat_kontrol_bpjs.no_surat from bridging_surat_kontrol_bpjs where bridging_surat_kontrol_bpjs.no_surat = ?", NoRMPasien.getText().trim());
                if (noSKDP.isBlank()) {
                    JOptionPane.showMessageDialog(null, "Data rujukan tidak ditemukan..!!");
                } else {
                    if (Sequel.cariExistsSmc("select * from referensi_mobilejkn_bpjs where nomorreferensi = ? and tanggalperiksa = current_date() and status in ('Belum', 'Checkin')", noSKDP)) {
                        JOptionPane.showMessageDialog(null, "Pasien telah mengambil antrian menggunakan Mobile JKN.\nSilahkan cekin melalui menu \"Cek In MobileJKN\"..!!");
                    } else if (Sequel.cariIntegerSmc("select datediff((select tgl_rencana from bridging_surat_kontrol_bpjs where no_surat = ?), current_date())", noSKDP) > 0) {
                        JOptionPane.showMessageDialog(null, "Jadwal kontrol pasien tidak boleh dimajukan..!!");
                    } else {
                        regist.tampilKontrol(noSKDP);
                        regist.setSize(getContentPane().getSize());
                        regist.setLocationRelativeTo(getContentPane());
                        regist.setVisible(true);
                        this.flag = -1;
                        this.dispose();
                    }
                }
            } else {
                String noKartu = Sequel.cariIsiSmc("select pasien.no_peserta from pasien where (pasien.no_ktp = ? or pasien.no_peserta = ? or pasien.no_rkm_medis = ?)", NoRMPasien.getText().trim(), NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
                if (noKartu.isBlank()) {
                    JOptionPane.showMessageDialog(null, "Data pasien tidak ditemukan..!!");
                } else {
                    if (Sequel.cariExistsSmc("select * from referensi_mobilejkn_bpjs where nomorkartu = ? and tanggalperiksa = current_date() and status in ('Belum', 'Checkin')", noKartu)) {
                        JOptionPane.showMessageDialog(null, "Pasien telah mengambil antrian menggunakan Mobile JKN.\nSilahkan cekin melalui menu \"Cek In MobileJKN\"..!!");
                    } else {
                        switch (flag) {
                            case SEP_KUNJUNGAN_PERTAMA:
                                regist.tampilKunjunganPertama(noKartu);
                                break;
                            case SEP_KONTROL_BEDA_POLI:
                                regist.tampilKunjunganBedaPoli(noKartu);
                                break;
                        }
                        regist.setSize(getContentPane().getSize());
                        regist.setLocationRelativeTo(getContentPane());
                        regist.setVisible(true);
                        this.flag = -1;
                        this.dispose();
                    }
                }
            }
        }
        formWindowActivated(null);
        this.setCursor(Cursor.getDefaultCursor());
    }
}
