package khanzahmsanjungan;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class DlgCekRegistrasiMandiri extends widget.Dialog {

    private final sekuel Sequel = new sekuel();
    private final DlgRegistrasiMandiri form;

    public DlgCekRegistrasiMandiri(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.form = new DlgRegistrasiMandiri(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new widget.Panel();
        PanelWall = new usu.widget.glass.PanelGlass();
        panelTengah = new widget.Panel();
        NoRMPasien = new widget.TextField();
        jLabel28 = new widget.Label();
        BtnBatal = new widget.Button();
        BtnKonfirm = new widget.Button();
        panelNumpad1 = new widget.Numpad();
        jLabel1 = new widget.Label();
        jLabel2 = new widget.Label();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        panelAtas.add(PanelWall);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0), "::[ Pendaftaran Eksekutif ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        panelTengah.setPreferredSize(new java.awt.Dimension(400, 70));
        panelTengah.setLayout(new java.awt.GridBagLayout());

        NoRMPasien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        NoRMPasien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoRMPasien.setFont(new java.awt.Font("Inter", 0, 36)); // NOI18N
        NoRMPasien.setPreferredSize(new java.awt.Dimension(600, 75));
        NoRMPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMPasienKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelTengah.add(NoRMPasien, gridBagConstraints);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("No. RM / NIK :");
        jLabel28.setFont(new java.awt.Font("Inter Medium", 0, 36)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(450, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel28, gridBagConstraints);

        BtnBatal.setBackground(new java.awt.Color(255, 255, 255));
        BtnBatal.setForeground(new java.awt.Color(255, 33, 32));
        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        BtnBatal.setMnemonic('U');
        BtnBatal.setText("BATAL");
        BtnBatal.setToolTipText("Alt+U");
        BtnBatal.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnBatal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBatal.setIconTextGap(2);
        BtnBatal.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panelTengah.add(BtnBatal, gridBagConstraints);

        BtnKonfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        BtnKonfirm.setMnemonic('U');
        BtnKonfirm.setText("CEK");
        BtnKonfirm.setToolTipText("Alt+U");
        BtnKonfirm.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        BtnKonfirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKonfirm.setIconTextGap(0);
        BtnKonfirm.setPreferredSize(new java.awt.Dimension(200, 75));
        BtnKonfirm.setVerifyInputWhenFocusTarget(false);
        BtnKonfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(BtnKonfirm, gridBagConstraints);

        panelNumpad1.setTextBox(NoRMPasien);
        panelNumpad1.setTextLimit(20L);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(panelNumpad1, gridBagConstraints);

        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel1, gridBagConstraints);

        jLabel2.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel2, gridBagConstraints);

        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel3, gridBagConstraints);

        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel4, gridBagConstraints);

        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel5, gridBagConstraints);

        jLabel6.setPreferredSize(new java.awt.Dimension(200, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        panelTengah.add(jLabel6, gridBagConstraints);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKonfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmActionPerformed
        cek();
    }//GEN-LAST:event_BtnKonfirmActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void NoRMPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMPasienKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cek();
        }
    }//GEN-LAST:event_NoRMPasienKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        NoRMPasien.setText("");
        NoRMPasien.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnKonfirm;
    private widget.TextField NoRMPasien;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.Label jLabel1;
    private widget.Label jLabel2;
    private widget.Label jLabel28;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Panel panelAtas;
    private widget.Numpad panelNumpad1;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables

    private void cek() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (NoRMPasien.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Isian masih kosong..!!");
            formWindowActivated(null);
        } else {
            String noRM = Sequel.cariIsiSmc("select pasien.no_rkm_medis from pasien where (pasien.no_rkm_medis = ? or trim(pasien.no_ktp) = ?)", NoRMPasien.getText().trim(), NoRMPasien.getText().trim());
            if (noRM.isBlank()) {
                JOptionPane.showMessageDialog(null, "Data pasien tidak ditemukan..!!");
                formWindowActivated(null);
            } else {
                form.setSize(this.getSize());
                form.setLocationRelativeTo(this);
                form.setPasien(noRM);
                form.setVisible(true);
                this.dispose();
            }
        }
        this.setCursor(Cursor.getDefaultCursor());
    }
}
