package khanzahmsanjungan;

import registrasieksekutif.DlgCekNoRM;
import registrasibpjs.DlgCekinMobileJKN;
import fungsi.koneksiDB;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import registrasibpjs.DlgCekSEPKontrol;
import registrasibpjs.DlgCekSEPKontrolBedaPoli;
import registrasibpjs.DlgCekSEPKunjunganPertama;

/**
 *
 * @author it-rsib
 */
public class HalamanUtamaDepan extends javax.swing.JFrame {

    private final ArrayList<String> TOMBOLDIMATIKAN = new ArrayList(Arrays.asList(koneksiDB.TOMBOLDIMATIKAN()));

    public HalamanUtamaDepan() {
        initComponents();
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/indriati48.png")).getImage());
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);

        TOMBOLDIMATIKAN.forEach(tombol -> {
            switch (tombol) {
                case "antrian":
                    jPanel1.remove(btnAntrian);
                    break;
                case "cekin":
                    jPanel1.remove(btnCekinBooking);
                    break;
                case "daftarpoli":
                    jPanel1.remove(btnDaftarEksekutif);
                    break;
                case "seppertama":
                    jPanel1.remove(btnSEPPertama);
                    break;
                case "sepkontrol":
                    jPanel1.remove(btnSEPKontrol);
                    break;
                case "sepbedapoli":
                    jPanel1.remove(btnSEPKontrolBedaPoli);
                    break;
                case "mobilejkn":
                    jPanel1.remove(btnCekinMobileJKN);
                    break;
                case "satusehat":
                    jPanel1.remove(btnSatuSehat);
                    break;
            }
        });

        if (jPanel1.getComponentCount() == 1) {
            jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        }

        jPanel1.repaint();

        pack();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAntrian = new widget.ButtonMenu();
        btnCekinBooking = new widget.ButtonMenu();
        btnDaftarEksekutif = new widget.ButtonMenu();
        btnSEPPertama = new widget.ButtonMenu();
        btnSEPKontrol = new widget.ButtonMenu();
        btnSEPKontrolBedaPoli = new widget.ButtonMenu();
        btnCekinMobileJKN = new widget.ButtonMenu();
        btnSatuSehat = new widget.ButtonMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setForeground(new java.awt.Color(238, 238, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel39.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 131, 62));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("ANJUNGAN PASIEN MANDIRI");
        jLabel39.setPreferredSize(new java.awt.Dimension(750, 75));
        jPanel3.add(jLabel39, java.awt.BorderLayout.CENTER);

        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Build 2025-06-12      ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setRequestFocusEnabled(false);
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        btnAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        btnAntrian.setText("ANTRIAN PASIEN");
        btnAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntrianActionPerformed(evt);
            }
        });
        jPanel1.add(btnAntrian);

        btnCekinBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checkin.png"))); // NOI18N
        btnCekinBooking.setText("CEK IN REGISTRASI");
        btnCekinBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekinBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnCekinBooking);

        btnDaftarEksekutif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        btnDaftarEksekutif.setText("PENDAFTARAN POLIKLINIK");
        btnDaftarEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarEksekutifActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarEksekutif);

        btnSEPPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/btn_bpjs_kesehatan.png"))); // NOI18N
        btnSEPPertama.setText("SEP KUNJUNGAN PERTAMA");
        btnSEPPertama.setIconTextGap(32);
        btnSEPPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPPertamaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPPertama);

        btnSEPKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/btn_bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrol.setText("SEP KONTROL");
        btnSEPKontrol.setIconTextGap(32);
        btnSEPKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPKontrol);

        btnSEPKontrolBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/btn_bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrolBedaPoli.setText("KONTROL BEDA POLI");
        btnSEPKontrolBedaPoli.setIconTextGap(32);
        btnSEPKontrolBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolBedaPoliActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPKontrolBedaPoli);

        btnCekinMobileJKN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/mobilejkn48.png"))); // NOI18N
        btnCekinMobileJKN.setText("CEK IN MOBILEJKN");
        btnCekinMobileJKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekinMobileJKNActionPerformed(evt);
            }
        });
        jPanel1.add(btnCekinMobileJKN);

        btnSatuSehat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logo-satset.png"))); // NOI18N
        btnSatuSehat.setText("AKTIVASI SATUSEHAT");
        btnSatuSehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuSehatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSatuSehat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEPKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolActionPerformed
        DlgCekSEPKontrol pilih = new DlgCekSEPKontrol(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolActionPerformed

    private void btnDaftarEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarEksekutifActionPerformed
        DlgCekNoRM pilih = new DlgCekNoRM(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnDaftarEksekutifActionPerformed

    private void btnCekinBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekinBookingActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
        // DlgCekBooking pilih = new DlgCekBooking(null, true);
        // pilih.setSize(this.getWidth(), this.getHeight());
        // pilih.setLocationRelativeTo(this);
        // pilih.setVisible(true);
    }//GEN-LAST:event_btnCekinBookingActionPerformed

    private void btnSEPPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPPertamaActionPerformed
        DlgCekSEPKunjunganPertama pilih = new DlgCekSEPKunjunganPertama(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnSEPPertamaActionPerformed

    private void btnCekinMobileJKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekinMobileJKNActionPerformed
        DlgCekinMobileJKN pilih = new DlgCekinMobileJKN(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnCekinMobileJKNActionPerformed

    private void btnSEPKontrolBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolBedaPoliActionPerformed
        DlgCekSEPKontrolBedaPoli pilih = new DlgCekSEPKontrolBedaPoli(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolBedaPoliActionPerformed

    private void btnAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntrianActionPerformed
        if (koneksiDB.ANTRIANPREFIXHURUF()) {
            DlgAmbilAntrean pilih = new DlgAmbilAntrean(null, true);
            pilih.setSize(this.getWidth(), this.getHeight());
            pilih.setLocationRelativeTo(this);
            pilih.setVisible(true);
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                Runtime.getRuntime().exec("java -jar KhanzaCetakAntrianLoket.jar");
            } catch (Exception e) {
                System.out.print("Notif : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnAntrianActionPerformed

    private void btnSatuSehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuSehatActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
        // this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='0132' ");
        // Valid.panggilUrl("kyc/index.php?&nikagent=" + nikktppetugas + "");
        // this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnSatuSehatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HalamanUtamaDepan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ButtonMenu btnAntrian;
    private widget.ButtonMenu btnCekinBooking;
    private widget.ButtonMenu btnCekinMobileJKN;
    private widget.ButtonMenu btnDaftarEksekutif;
    private widget.ButtonMenu btnSEPKontrol;
    private widget.ButtonMenu btnSEPKontrolBedaPoli;
    private widget.ButtonMenu btnSEPPertama;
    private widget.ButtonMenu btnSatuSehat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
