package khanzahmsanjungan;

import fungsi.koneksiDB;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author it-rsib
 */
public class HalamanUtamaDepan extends javax.swing.JFrame {

    private static HalamanUtamaDepan myInstance;
    private final ArrayList<String> TOMBOLDIMATIKAN = new ArrayList(Arrays.asList(koneksiDB.TOMBOLDIMATIKAN()));
    private DlgAmbilAntrian antrian = null;
    private DlgCekBooking booking = null;
    private DlgCekNoRM daftarpoli = null;
    private DlgCekKunjunganPertamaSEP seppertama = null;
    private DlgCekSKDPKontrol sepkontrol = null;
    private DlgCekKunjunganBedaPoli sepbedapoli = null;
    private DlgCekinMobileJKN mobilejkn = null;

    public HalamanUtamaDepan() {
        initComponents();
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/indriati48.png")).getImage());
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        
        TOMBOLDIMATIKAN.forEach(tombol -> {
            switch (tombol) {
                case "antrian":
                    jPanel1.remove(btnAntrian);
                    break;
                case "cekin":
                    jPanel1.remove(btnCekinBooking);
                    break;
                case "daftarpoli":
                    jPanel1.remove(btnDaftarEksekutif);
                    break;
                case "seppertama":
                    jPanel1.remove(btnSEPPertama);
                    break;
                case "sepkontrol":
                    jPanel1.remove(btnSEPKontrol);
                    break;
                case "sepbedapoli":
                    jPanel1.remove(btnSEPKontrolBedaPoli);
                    break;
                case "mobilejkn":
                    jPanel1.remove(btnCekinMobileJKN);
                    break;
                case "satusehat":
                    jPanel1.remove(btnSatuSehat);
                    break;
            }
        });
        
        if (jPanel1.getComponentCount() == 1) {
            jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        }
        
        jPanel1.repaint();
        
        pack();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new widget.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new javax.swing.JPanel();
        btnAntrian = new widget.ButtonBig();
        btnCekinBooking = new widget.ButtonBig();
        btnDaftarEksekutif = new widget.ButtonBig();
        btnSEPPertama = new widget.ButtonBig();
        btnSEPKontrol = new widget.ButtonBig();
        btnSEPKontrolBedaPoli = new widget.ButtonBig();
        btnCekinMobileJKN = new widget.ButtonBig();
        btnSatuSehat = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setForeground(new java.awt.Color(238, 238, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel39.setForeground(new java.awt.Color(0, 131, 62));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("ANJUNGAN PASIEN MANDIRI");
        jLabel39.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel39.setPreferredSize(new java.awt.Dimension(750, 75));
        jPanel3.add(jLabel39, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Build 2025-06-26 Patch 2      ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(150, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        btnAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        btnAntrian.setText("ANTRIAN PASIEN");
        btnAntrian.setIconTextGap(0);
        btnAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntrianActionPerformed(evt);
            }
        });
        jPanel1.add(btnAntrian);

        btnCekinBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checkin.png"))); // NOI18N
        btnCekinBooking.setText("CEK IN BOOKING");
        btnCekinBooking.setIconTextGap(0);
        btnCekinBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekinBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnCekinBooking);

        btnDaftarEksekutif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        btnDaftarEksekutif.setText("PENDAFTARAN EKSEKUTIF");
        btnDaftarEksekutif.setIconTextGap(0);
        btnDaftarEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarEksekutifActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarEksekutif);

        btnSEPPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/BPJS_Kesehatan_Logo.png"))); // NOI18N
        btnSEPPertama.setText("SEP KUNJUNGAN PERTAMA");
        btnSEPPertama.setIconTextGap(0);
        btnSEPPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPPertamaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPPertama);

        btnSEPKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/BPJS_Kesehatan_Logo.png"))); // NOI18N
        btnSEPKontrol.setText("SEP KONTROL");
        btnSEPKontrol.setIconTextGap(0);
        btnSEPKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPKontrol);

        btnSEPKontrolBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/BPJS_Kesehatan_Logo.png"))); // NOI18N
        btnSEPKontrolBedaPoli.setText("KONTROL BEDA POLI");
        btnSEPKontrolBedaPoli.setIconTextGap(0);
        btnSEPKontrolBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolBedaPoliActionPerformed(evt);
            }
        });
        jPanel1.add(btnSEPKontrolBedaPoli);

        btnCekinMobileJKN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/mobilejkn48.png"))); // NOI18N
        btnCekinMobileJKN.setText("CEK IN MOBILEJKN");
        btnCekinMobileJKN.setIconTextGap(0);
        btnCekinMobileJKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekinMobileJKNActionPerformed(evt);
            }
        });
        jPanel1.add(btnCekinMobileJKN);

        btnSatuSehat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logo-satset.png"))); // NOI18N
        btnSatuSehat.setText("AKTIVASI SATUSEHAT");
        btnSatuSehat.setIconTextGap(0);
        btnSatuSehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuSehatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSatuSehat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEPKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolActionPerformed
        if (sepkontrol == null) {
            sepkontrol = new DlgCekSKDPKontrol(null, true);
        }
        sepkontrol.setSize(this.getWidth(), this.getHeight());
        sepkontrol.setLocationRelativeTo(this);
        sepkontrol.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolActionPerformed

    private void btnDaftarEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarEksekutifActionPerformed
        if (daftarpoli == null) {
            daftarpoli = new DlgCekNoRM(null, true);
        }
        daftarpoli.setSize(this.getWidth(), this.getHeight());
        daftarpoli.setLocationRelativeTo(this);
        daftarpoli.setVisible(true);
    }//GEN-LAST:event_btnDaftarEksekutifActionPerformed

    private void btnCekinBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekinBookingActionPerformed
        if (booking == null) {
            booking = new DlgCekBooking(null, true);
        }
        booking.setSize(this.getWidth(), this.getHeight());
        booking.setLocationRelativeTo(this);
        booking.setVisible(true);
    }//GEN-LAST:event_btnCekinBookingActionPerformed

    private void btnSEPPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPPertamaActionPerformed
        if (seppertama == null) {
            seppertama = new DlgCekKunjunganPertamaSEP(null, true);
        }
        seppertama.setSize(this.getWidth(), this.getHeight());
        seppertama.setLocationRelativeTo(this);
        seppertama.setVisible(true);
    }//GEN-LAST:event_btnSEPPertamaActionPerformed

    private void btnCekinMobileJKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekinMobileJKNActionPerformed
        if (mobilejkn == null) {
            mobilejkn = new DlgCekinMobileJKN(null, true);
        }
        mobilejkn.setSize(this.getWidth(), this.getHeight());
        mobilejkn.setLocationRelativeTo(this);
        mobilejkn.setVisible(true);
    }//GEN-LAST:event_btnCekinMobileJKNActionPerformed

    private void btnSEPKontrolBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolBedaPoliActionPerformed
        if (sepbedapoli == null) {
            sepbedapoli = new DlgCekKunjunganBedaPoli(null, true);
        }
        sepbedapoli.setSize(this.getWidth(), this.getHeight());
        sepbedapoli.setLocationRelativeTo(this);
        sepbedapoli.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolBedaPoliActionPerformed

    private void btnAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntrianActionPerformed
        if (koneksiDB.ANTRIANPREFIXHURUF()) {
            if (antrian == null) {
                antrian = new DlgAmbilAntrian(null, true);
            }
            antrian.setSize(this.getWidth(), this.getHeight());
            antrian.setLocationRelativeTo(this);
            antrian.setVisible(true);
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                Runtime.getRuntime().exec("java -jar KhanzaCetakAntrianLoket.jar");
            } catch (Exception e) {
                System.out.print("Notif : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnAntrianActionPerformed

    private void btnSatuSehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuSehatActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Mohon maaf, fitur masih dalam tahap pengembangan");
        // this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='0132' ");
        // Valid.panggilUrl("kyc/index.php?&nikagent=" + nikktppetugas + "");
        // this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnSatuSehatActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new HalamanUtamaDepan().setVisible(true));
    }

    public static HalamanUtamaDepan getInstance() {
        if (myInstance == null) {
            myInstance = new HalamanUtamaDepan();
        }

        return myInstance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.ButtonBig btnAntrian;
    private widget.ButtonBig btnCekinBooking;
    private widget.ButtonBig btnCekinMobileJKN;
    private widget.ButtonBig btnDaftarEksekutif;
    private widget.ButtonBig btnSEPKontrol;
    private widget.ButtonBig btnSEPKontrolBedaPoli;
    private widget.ButtonBig btnSEPPertama;
    private widget.ButtonBig btnSatuSehat;
    private javax.swing.JLabel jLabel1;
    private widget.Label jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
