package khanzahmsanjungan;

import fungsi.koneksiDB;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author it-rsib
 */
public class HalamanUtama extends javax.swing.JFrame {

    private final ArrayList<String> TOMBOLDIMATIKAN = new ArrayList(Arrays.asList(koneksiDB.TOMBOLDIMATIKAN()));
    private final DlgCekDataPasien umum;
    private final DlgCekDataPasienBPJS bpjs;
    private final DlgAmbilAntrian antrian;

    public HalamanUtama() {
        initComponents();
        
        umum = new DlgCekDataPasien(this, false);
        bpjs = new DlgCekDataPasienBPJS(this, false);
        antrian = new DlgAmbilAntrian(this, false);
        
        TOMBOLDIMATIKAN.forEach(tombol -> {
            switch (tombol) {
                case "antrian":
                    panelTengah.remove(btnAntrian);
                    break;
                case "cekin":
                    panelTengah.remove(btnBooking);
                    break;
                case "daftarpoli":
                    panelTengah.remove(btnDaftarpoli);
                    break;
                case "seppertama":
                    panelTengah.remove(btnSEPPertama);
                    break;
                case "sepkontrol":
                    panelTengah.remove(btnSEPKontrol);
                    break;
                case "sepbedapoli":
                    panelTengah.remove(btnSEPKontrolBedaPoli);
                    break;
                case "mobilejkn":
                    panelTengah.remove(btnMobilejkn);
                    break;
                case "satusehat":
                    panelTengah.remove(btnSatusehat);
                    break;
            }
        });

        if (panelTengah.getComponentCount() == 1) {
            panelTengah.setLayout(new java.awt.GridLayout(0, 1));
        }

        panelTengah.repaint();

        pack();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new widget.Panel();
        logo = new usu.widget.glass.PanelGlass();
        panelTengah = new widget.Panel();
        btnAntrian = new widget.MenuButton();
        btnBooking = new widget.MenuButton();
        btnDaftarpoli = new widget.MenuButton();
        btnSEPPertama = new widget.MenuButton();
        btnSEPKontrol = new widget.MenuButton();
        btnSEPKontrolBedaPoli = new widget.MenuButton();
        btnMobilejkn = new widget.MenuButton();
        btnSatusehat = new widget.MenuButton();
        panelBawah = new widget.Panel();
        judul = new widget.Label();
        versi = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANJUNGAN PASIEN MANDIRI");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/indriati48.png")).getImage());

        panelAtas.setPreferredSize(new java.awt.Dimension(130, 130));
        panelAtas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        logo.setBackground(new java.awt.Color(240, 249, 255));
        logo.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/icon-128x128.png"))); // NOI18N
        logo.setForeground(new java.awt.Color(238, 238, 255));
        logo.setPreferredSize(new java.awt.Dimension(120, 120));
        logo.setRound(false);
        logo.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panelAtas.add(logo);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setPreferredSize(new java.awt.Dimension(1280, 1024));
        panelTengah.setLayout(new java.awt.GridLayout(0, 2));

        btnAntrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/antrianpasien.png"))); // NOI18N
        btnAntrian.setText("ANTRIAN PASIEN");
        btnAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntrianActionPerformed(evt);
            }
        });
        panelTengah.add(btnAntrian);

        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/checkin.png"))); // NOI18N
        btnBooking.setText("CEK IN BOOKING");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        panelTengah.add(btnBooking);

        btnDaftarpoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/kioskselfservice.png"))); // NOI18N
        btnDaftarpoli.setText("PENDAFTARAN EKSEKUTIF");
        btnDaftarpoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarpoliActionPerformed(evt);
            }
        });
        panelTengah.add(btnDaftarpoli);

        btnSEPPertama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPPertama.setText("SEP KUNJUNGAN PERTAMA");
        btnSEPPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPPertamaActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPPertama);

        btnSEPKontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrol.setText("SEP KONTROL");
        btnSEPKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPKontrol);

        btnSEPKontrolBedaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/bpjs_kesehatan.png"))); // NOI18N
        btnSEPKontrolBedaPoli.setText("KONTROL BEDA POLI");
        btnSEPKontrolBedaPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEPKontrolBedaPoliActionPerformed(evt);
            }
        });
        panelTengah.add(btnSEPKontrolBedaPoli);

        btnMobilejkn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/mobilejkn48.png"))); // NOI18N
        btnMobilejkn.setText("CEK IN MOBILEJKN");
        btnMobilejkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobilejknActionPerformed(evt);
            }
        });
        panelTengah.add(btnMobilejkn);

        btnSatusehat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/logo-satset.png"))); // NOI18N
        btnSatusehat.setText("AKTIVASI SATUSEHAT");
        btnSatusehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatusehatActionPerformed(evt);
            }
        });
        panelTengah.add(btnSatusehat);

        getContentPane().add(panelTengah, java.awt.BorderLayout.CENTER);

        panelBawah.setLayout(new java.awt.BorderLayout());

        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("ANJUNGAN PASIEN MANDIRI");
        judul.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(750, 40));
        panelBawah.add(judul, java.awt.BorderLayout.CENTER);

        versi.setForeground(new java.awt.Color(150, 155, 159));
        versi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        versi.setText("Build 2025-07-15      ");
        versi.setFocusable(false);
        panelBawah.add(versi, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelBawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSEPKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolActionPerformed
        bpjs.setFlag(DlgCekDataPasienBPJS.SEP_KONTROL);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolActionPerformed

    private void btnDaftarpoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarpoliActionPerformed
        umum.setFlag(DlgCekDataPasien.REGIST_MANDIRI);
        umum.setSize(getContentPane().getSize());
        umum.setLocationRelativeTo(getContentPane());
        umum.setVisible(true);
    }//GEN-LAST:event_btnDaftarpoliActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        umum.setFlag(DlgCekDataPasien.CEKIN_BOOKING);
        umum.setSize(getContentPane().getSize());
        umum.setLocationRelativeTo(getContentPane());
        umum.setVisible(true);
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnSEPPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPPertamaActionPerformed
        bpjs.setFlag(DlgCekDataPasienBPJS.SEP_KUNJUNGAN_PERTAMA);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPPertamaActionPerformed

    private void btnMobilejknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilejknActionPerformed
        bpjs.setFlag(DlgCekDataPasienBPJS.SEP_MOBILEJKN);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnMobilejknActionPerformed

    private void btnSEPKontrolBedaPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEPKontrolBedaPoliActionPerformed
        bpjs.setFlag(DlgCekDataPasienBPJS.SEP_KONTROL_BEDA_POLI);
        bpjs.setSize(getContentPane().getSize());
        bpjs.setLocationRelativeTo(getContentPane());
        bpjs.setVisible(true);
    }//GEN-LAST:event_btnSEPKontrolBedaPoliActionPerformed

    private void btnAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntrianActionPerformed
        if (koneksiDB.ANTRIANPREFIXHURUF()) {
            antrian.setSize(getContentPane().getSize());
            antrian.setLocationRelativeTo(getContentPane());
            antrian.setVisible(true);
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                Runtime.getRuntime().exec("java -jar KhanzaCetakAntrianLoket.jar");
            } catch (Exception e) {
                System.out.print("Notif : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_btnAntrianActionPerformed

    private void btnSatusehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatusehatActionPerformed
        JOptionPane.showMessageDialog(null, "Mohon maaf, fitur masih dalam tahap pengembangan");
        // this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // String nikktppetugas = Sequel.cariIsi("select no_ktp from pegawai where nik='0132' ");
        // Valid.panggilUrl("kyc/index.php?&nikagent=" + nikktppetugas + "");
        // this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnSatusehatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.MenuButton btnAntrian;
    private widget.MenuButton btnBooking;
    private widget.MenuButton btnDaftarpoli;
    private widget.MenuButton btnMobilejkn;
    private widget.MenuButton btnSEPKontrol;
    private widget.MenuButton btnSEPKontrolBedaPoli;
    private widget.MenuButton btnSEPPertama;
    private widget.MenuButton btnSatusehat;
    private widget.Label judul;
    private usu.widget.glass.PanelGlass logo;
    private widget.Panel panelAtas;
    private widget.Panel panelBawah;
    private widget.Panel panelTengah;
    private widget.Label versi;
    // End of variables declaration//GEN-END:variables
}
